// Display + input metadata for the 12 training features.
// Keys match the dataset column aliases returned by FastAPI.

export const FEATURE_META = {
  Neighborhood: {
    label: 'Neighborhood',
    input: 'text',
    placeholder: 'OldTown',
    helper: 'Use an Ames code like OldTown, NridgHt, or CollgCr.',
  },
  HouseStyle: {
    label: 'House style',
    input: 'text',
    placeholder: '1Story',
    helper: 'Examples: 1Story, 2Story, 1.5Fin, SLvl.',
  },
  YearBuilt: {
    label: 'Year built',
    input: 'number',
    valueType: 'int',
    min: 1800,
    max: 2030,
    step: 1,
    placeholder: '2005',
  },
  GrLivArea: {
    label: 'Living area',
    unit: 'sq ft',
    input: 'number',
    valueType: 'float',
    min: 0,
    step: 1,
    placeholder: '1800',
  },
  TotalBsmtSF: {
    label: 'Basement',
    unit: 'sq ft',
    input: 'number',
    valueType: 'float',
    min: 0,
    step: 1,
    placeholder: '900',
  },
  BedroomAbvGr: {
    label: 'Bedrooms',
    input: 'number',
    valueType: 'int',
    min: 0,
    max: 20,
    step: 1,
    placeholder: '3',
  },
  FullBath: {
    label: 'Full baths',
    input: 'number',
    valueType: 'int',
    min: 0,
    max: 10,
    step: 1,
    placeholder: '2',
  },
  HalfBath: {
    label: 'Half baths',
    input: 'number',
    valueType: 'int',
    min: 0,
    max: 10,
    step: 1,
    placeholder: '1',
  },
  GarageCars: {
    label: 'Garage',
    unit: 'cars',
    input: 'number',
    valueType: 'int',
    min: 0,
    max: 10,
    step: 1,
    placeholder: '2',
  },
  Fireplaces: {
    label: 'Fireplaces',
    input: 'number',
    valueType: 'int',
    min: 0,
    max: 10,
    step: 1,
    placeholder: '1',
  },
  OverallQual: {
    label: 'Overall quality',
    scale: 10,
    input: 'number',
    valueType: 'int',
    min: 1,
    max: 10,
    step: 1,
    placeholder: '7',
    helper: '1 is poor, 10 is excellent.',
  },
  OverallCond: {
    label: 'Overall condition',
    scale: 10,
    input: 'number',
    valueType: 'int',
    min: 1,
    max: 10,
    step: 1,
    placeholder: '5',
    helper: '1 is poor, 10 is excellent.',
  },
}

// Order matters — this is the visual reading order in the feature grid.
// Place & character first, then footprint, then rooms, then quality.
export const FEATURE_ORDER = [
  'Neighborhood',
  'HouseStyle',
  'YearBuilt',
  'GrLivArea',
  'TotalBsmtSF',
  'BedroomAbvGr',
  'FullBath',
  'HalfBath',
  'GarageCars',
  'Fireplaces',
  'OverallQual',
  'OverallCond',
]
